export const rolePermissions = {
  "Admin": { "*": ["isView", "isEdit", "isDelete"] },
  "Super Admin": { "*": ["isView", "isEdit", "isDelete"] },
  "Asset Management": {
    assets: ["isView", "isEdit"],
    users: ["isView"],
  },
  "Employee": {
    incident: ["isView", "isEdit"],
    dashboard: ["isView"],
    serviceRequest: ["isView", "isEdit"],
    gatePass: ["isView", "isEdit"],
    globalIncident: ["isView", "isEdit"],
    incidentCategory: ["isView", "isEdit"],
    incidentStatus: ["isView", "isEdit"],
    location: ["isView", "isEdit"],
    sla: ["isView", "isEdit"],
    department: ["isView", "isEdit"],
    // component: ["isView", "isEdit"],
    softwareCategory: ["isView", "isEdit"],
    status: ["isView", "isEdit"],
    // storeLocation: ["isView", "isEdit"],
    supportDepartment: ["isView", "isEdit"],
    // vendorCategory: ["isView", "isEdit"],
    // vendor: ["isView", "isEdit"],
    // vendorServiceCategory: ["isView", "isEdit"],
    globalService: ["isView", "isEdit"],
    serviceRequest: ["isView", "isEdit"],
    assets: ["isView", "isEdit"],
  },
  "GoCollect Support Department": {
    supportDepartment: ["isView"],
  },
  "Grievance Support Team": {
    grievance: ["isView"],
  },
  "L1 Technician": {
    incident: ["isView", "isEdit"],
    dashboard: ["isView"],
    serviceRequest: ["isView", "isEdit"],
    gatePass: ["isView", "isEdit"],
    globalIncident: ["isView", "isEdit"],
    incidentCategory: ["isView", "isEdit"],
    incidentStatus: ["isView", "isEdit"],
    location: ["isView", "isEdit"],
    sla: ["isView", "isEdit"],
    department: ["isView", "isEdit"],
    // component: ["isView", "isEdit"],
    softwareCategory: ["isView", "isEdit"],
    status: ["isView", "isEdit"],
    // storeLocation: ["isView", "isEdit"],
    supportDepartment: ["isView", "isEdit"],
    // vendorCategory: ["isView", "isEdit"],
    // vendor: ["isView", "isEdit"],
    // vendorServiceCategory: ["isView", "isEdit"],
    globalService: ["isView", "isEdit"],
    serviceRequest: ["isView", "isEdit"],
    assets: ["isView", "isEdit"],
  },
  "L2 Technician": {
    incident: ["isView", "isEdit"],
    dashboard: ["isView"],
    serviceRequest: ["isView", "isEdit"],
    gatePass: ["isView", "isEdit"],
    globalIncident: ["isView", "isEdit"],
    incidentCategory: ["isView", "isEdit"],
    incidentStatus: ["isView", "isEdit"],
    location: ["isView", "isEdit"],
    sla: ["isView", "isEdit"],
    department: ["isView", "isEdit"],
    // component: ["isView", "isEdit"],
    softwareCategory: ["isView", "isEdit"],
    status: ["isView", "isEdit"],
    // storeLocation: ["isView", "isEdit"],
    supportDepartment: ["isView", "isEdit"],
    // vendorCategory: ["isView", "isEdit"],
    // vendor: ["isView", "isEdit"],
    // vendorServiceCategory: ["isView", "isEdit"],
    globalService: ["isView", "isEdit"],
    serviceRequest: ["isView", "isEdit"],
    assets: ["isView", "isEdit"],

  },
  "L3 Technician": {
    incident: ["isView", "isEdit"],
    dashboard: ["isView"],
    serviceRequest: ["isView", "isEdit"],
    gatePass: ["isView", "isEdit"],
    globalIncident: ["isView", "isEdit"],
    incidentCategory: ["isView", "isEdit"],
    incidentStatus: ["isView", "isEdit"],
    location: ["isView", "isEdit"],
    sla: ["isView", "isEdit"],
    department: ["isView", "isEdit"],
    // component: ["isView", "isEdit"],
    softwareCategory: ["isView", "isEdit"],
    status: ["isView", "isEdit"],
    // storeLocation: ["isView", "isEdit"],
    supportDepartment: ["isView", "isEdit"],
    // vendorCategory: ["isView", "isEdit"],
    // vendor: ["isView", "isEdit"],
    // vendorServiceCategory: ["isView", "isEdit"],
    globalService: ["isView", "isEdit"],
    serviceRequest: ["isView", "isEdit"],
    assets: ["isView", "isEdit"],
  },
  "Application Support Team": {
    application: ["isView"],
  }
};

export const getPermissions = async (req, res) => {
  const { userRole } = req.user;
  let permissions = rolePermissions[userRole] || {};

  if (userRole === "Admin" || userRole === "Super Admin") {
    permissions = { "*": ["isView", "isEdit", "isDelete"] };
  }

  res.json({ permissions });
};